# Generated by Django 4.2.10 on 2024-03-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pacienti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_pacient', models.CharField(max_length=100)),
                ('prenume_pacient', models.CharField(max_length=100)),
                ('email_pacient', models.EmailField(max_length=100)),
                ('telefon_pacient', models.CharField(max_length=12)),
                ('data_nastere', models.DateField()),
                ('sex_pacient', models.BooleanField()),
            ],
        ),
    ]
