# Generated by Django 4.2.10 on 2024-03-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_medic', models.CharField(max_length=100)),
                ('prenume_medic', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email_medic', models.EmailField(max_length=100)),
                ('telefon_medic', models.CharField(max_length=12)),
            ],
        ),
    ]
